name: TheAlchemist
favicon: null
layout_spectrum: 0.7083626601379365
typography_spectrum: 0.9573698886670172
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5208593215793371
  lightness: 0.34691530279815197
  saturation: 0.9048134677577764
  rhythmicContrast: 0.6469174320809543
purpose: []
